### PR TITLE
Updated script for Galileo Gen2/Edison support

### PR DESCRIPTION
**Pull request by bbaltz505**
the previously closed defect (DP-3567) only fixed the sample sketch IotKitSimpleExample.ino for Edison devices. The sketch seems out-of-date on Galileo Gen2 boards.

### CODE REVIEW

**Comment by bbaltz505** [comment]
We also need to create an update IotKit.zip file as that is how the user imports the library and examples - per the README

**Comment by mtomczew** [comment]
Have you tested this sketch on both Edison and Galileo? I don't have a chance to do it in the nearest future.

**Comment by mtomczew** [comment]
Keeping binary files in git repository is a weird idea. However, you can prepare required zip archieve and add in another commit in this request if it's needed for compatibility reasons.

**Comment by bbaltz505** [comment]
Yes. I tested on a Galileo Gen2 and an Edison.The sketch can support only one device at a time. The default is for Galileo. The user will need to edit the temperature sensor path in the script for Edison.

**Comment by bbaltz505** [comment]
I agree. Usually you shouldn't store binary files in Git but I'm not sure where/how else to host the library zip.

**Comment by mtomczew** [comment]
Merged

**Pull request closed without merging**
